In [20]:
import pandas as pd

## 文件读写

### 创建测试数据

In [7]:
data = {
    "姓名": ["张三", "李四", "王五", "赵六"],
    "年龄": [20, 21, 19, 22],
    "成绩": [85.5, 92.0, 78.5, 88.0],
}
student = pd.DataFrame(data)
student.head()

   姓名  年龄    成绩
0  张三  20  85.5
1  李四  21  92.0
2  王五  19  78.5
3  赵六  22  88.0

### 保存文件

In [19]:
student.to_csv("student.csv", index=False, encoding="utf-8-sig")

### 读取CSV文件

In [18]:
student = pd.read_csv("student.csv", encoding="utf-8-sig")
student.head(2)

   姓名  年龄    成绩
0  张三  20  85.5
1  李四  21  92.0

In [17]:
# 数据集形状
student.shape

(4, 3)

## 数据切片

### 列切片

In [9]:
single_col = student["姓名"]
single_col

0    张三
1    李四
2    王五
3    赵六
Name: 姓名, dtype: str

In [10]:
multi_col = student[["姓名", "成绩"]]
multi_col

   姓名    成绩
0  张三  85.5
1  李四  92.0
2  王五  78.5
3  赵六  88.0

### 行切片

In [12]:
# 行标签1-2
loc_slice = student.loc[1:2, :]
loc_slice

   姓名  年龄    成绩
1  李四  21  92.0
2  王五  19  78.5

In [13]:
# 行0-1，列1-2
iloc_slice = student.iloc[0:2, 1:3]
iloc_slice

   年龄    成绩
0  20  85.5
1  21  92.0

### 条件切片

In [15]:
cond_slice = student[student["成绩"] > 85]
cond_slice

   姓名  年龄    成绩
0  张三  20  85.5
1  李四  21  92.0
3  赵六  22  88.0